<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="QZ-LT-R-CTK-023" failures="1" tests="3" name="End_To_End_SeleniumFramework.Code9IRetryAnalyzerToRerunTheFlakyFailedSeleniumTestsInFramework" time="32.725" errors="0" timestamp="18 Nov 2024 06:55:29 GMT" skipped="1">
  <testcase classname="End_To_End_SeleniumFramework.Code9IRetryAnalyzerToRerunTheFlakyFailedSeleniumTestsInFramework" name="logInPage" time="5.575">
    <failure message="expected [Incorrect email or password.] but found [Incorrect email  password.]" type="java.lang.AssertionError">
      <![CDATA[java.lang.AssertionError: expected [Incorrect email or password.] but found [Incorrect email  password.]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at End_To_End_SeleniumFramework.Code9IRetryAnalyzerToRerunTheFlakyFailedSeleniumTestsInFramework.logInPage(Code9IRetryAnalyzerToRerunTheFlakyFailedSeleniumTestsInFramework.java:28)
at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
at java.base/java.lang.reflect.Method.invoke(Method.java:580)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.retryFailed(Invoker.java:839)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1010)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
    </failure>
  </testcase> <!-- logInPage -->
  <testcase classname="End_To_End_SeleniumFramework.Code9IRetryAnalyzerToRerunTheFlakyFailedSeleniumTestsInFramework" name="productCatalog" time="14.850"/>
  <testcase classname="End_To_End_SeleniumFramework.Code9IRetryAnalyzerToRerunTheFlakyFailedSeleniumTestsInFramework" name="logInPage" time="12.300">
    <skipped/>
  </testcase> <!-- logInPage -->
</testsuite> <!-- End_To_End_SeleniumFramework.Code9IRetryAnalyzerToRerunTheFlakyFailedSeleniumTestsInFramework -->
